name: trufor_server
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.2
  - torchvision>=0.17
  - numpy
  - pillow
  - pyyaml
  - scipy
  - pip
  - pip:
    - timm>=0.5.4
    - yacs>=0.1.8
    - albumentations>=1.3.0
    - opencv-python>=4.8.0
    - fastapi>=0.109.0
    - uvicorn[standard]>=0.27.0
